// <auto-generated />
using CallingReact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CallingReact.Migrations
{
    [DbContext(typeof(AcsUserContext))]
    partial class AcsUserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CallingReact.Models.AcsUser", b =>
                {
                    b.Property<string>("userName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("connectionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.ToTable("AcsUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
